# Suppression Rule Templates
#
# This seed file creates common suppression rule templates that organizations
# can use as starting points for their own rules.
#
# Run with: mix run priv/repo/seeds/suppression_templates.exs

alias TamanduaServer.Repo
alias TamanduaServer.Alerts.SuppressionRule
alias TamanduaServer.Accounts.Organization

# Get or create a system organization for templates
system_org = Repo.get_by(Organization, name: "System") ||
  %Organization{}
  |> Organization.changeset(%{name: "System", slug: "system"})
  |> Repo.insert!()

templates = [
  %{
    name: "Development Environment Suppressions",
    template_name: "dev_environment",
    template_description: "Suppress alerts from development/test environments",
    action: "suppress",
    priority: 10,
    is_template: true,
    description: """
    Use this template to suppress alerts from development or test environments.
    Customize the agent_id or add tags to match your dev environment agents.
    """,
    tags: ["dev", "test", "staging"],
    time_window_type: "indefinite"
  },

  %{
    name: "Known Benign Software - Antivirus",
    template_name: "benign_antivirus",
    template_description: "Suppress alerts from antivirus software performing scans",
    action: "suppress",
    priority: 20,
    is_template: true,
    description: """
    Suppress alerts generated by antivirus software during routine operations.
    Commonly matches process injection or file access patterns.
    """,
    process_name_pattern: "*defender*",
    time_window_type: "indefinite"
  },

  %{
    name: "Known Benign Software - Backup Agents",
    template_name: "benign_backup",
    template_description: "Suppress alerts from backup software",
    action: "suppress",
    priority: 20,
    is_template: true,
    description: """
    Suppress alerts from backup agents that may trigger file access or
    process creation detections.
    """,
    process_name_pattern: "*backup*",
    time_window_type: "indefinite"
  },

  %{
    name: "Reduce Severity - Informational Scans",
    template_name: "reduce_severity_scans",
    template_description: "Reduce severity of port scans and enumeration from known sources",
    action: "reduce_severity",
    reduce_to_severity: "low",
    priority: 15,
    is_template: true,
    description: """
    Reduce the severity of port scans and network enumeration from vulnerability
    scanners or security tools. Does not suppress entirely.
    """,
    title_pattern: "*port scan*",
    time_window_type: "indefinite"
  },

  %{
    name: "Maintenance Window - Temporary Suppression",
    template_name: "maintenance_window",
    template_description: "Temporarily suppress alerts during scheduled maintenance",
    action: "suppress",
    priority: 50,
    is_template: true,
    description: """
    Use this template to suppress alerts during scheduled maintenance windows.
    Set the time_window_value to match your maintenance duration (in seconds).
    Example: 3600 = 1 hour, 86400 = 24 hours
    """,
    time_window_type: "duration",
    time_window_value: 3600
  },

  %{
    name: "Executive/VIP Exemption",
    template_name: "vip_exemption",
    template_description: "Lower alert severity for executive devices (with exemptions)",
    action: "reduce_severity",
    reduce_to_severity: "medium",
    priority: 80,
    is_template: true,
    description: """
    Reduce alert severity for executive devices while maintaining visibility.
    Add executive agent IDs to exempted_agent_ids when instantiating.
    This does NOT suppress alerts entirely - it reduces noise while keeping SOC informed.
    """,
    time_window_type: "indefinite"
  },

  %{
    name: "PowerShell - Known Admin Scripts",
    template_name: "powershell_admin_scripts",
    template_description: "Suppress alerts from known administrative PowerShell scripts",
    action: "suppress",
    priority: 25,
    is_template: true,
    description: """
    Suppress PowerShell execution alerts for known administrative scripts.
    Customize file_path_pattern to match your script locations.
    """,
    process_name_pattern: "*powershell*",
    file_path_pattern: "*\\AdminScripts\\*",
    time_window_type: "indefinite"
  },

  %{
    name: "Reduce Severity - Low Confidence Detections",
    template_name: "low_confidence",
    template_description: "Reduce severity for low-confidence ML detections",
    action: "reduce_severity",
    reduce_to_severity: "low",
    priority: 5,
    is_template: true,
    description: """
    Reduce severity for ML-based detections with low confidence scores.
    Helps reduce false positives while maintaining visibility.
    """,
    criteria: %{
      "threat_score_lt" => 0.5,
      "source" => "ml"
    },
    time_window_type: "indefinite"
  },

  %{
    name: "Tag - Security Tools Activity",
    template_name: "tag_security_tools",
    template_description: "Tag alerts from security tools for easier filtering",
    action: "tag",
    add_tags: ["security_tool", "benign"],
    priority: 10,
    is_template: true,
    description: """
    Add tags to alerts generated by security tools (scanners, EDR, etc.).
    Does not suppress - just adds context for easier filtering and investigation.
    """,
    process_name_pattern: "*nessus*",
    time_window_type: "indefinite"
  },

  %{
    name: "MITRE T1055 - Process Injection FP",
    template_name: "t1055_fp",
    template_description: "Suppress known false positives for process injection technique",
    action: "suppress",
    priority: 20,
    is_template: true,
    description: """
    Suppress known false positive process injection alerts (T1055).
    Customize with specific process names or paths that commonly trigger FPs.
    """,
    mitre_techniques: ["T1055"],
    time_window_type: "indefinite"
  },

  %{
    name: "Rate Limit - Noisy Rule",
    template_name: "rate_limit",
    template_description: "Rate limit a noisy detection rule using max_matches",
    action: "reduce_severity",
    reduce_to_severity: "low",
    priority: 15,
    is_template: true,
    description: """
    Use max_matches to rate limit noisy detection rules.
    After N matches, the rule stops applying and alerts go through normally.
    This is useful for temporarily reducing noise from a specific rule.
    """,
    max_matches: 100,
    time_window_type: "duration",
    time_window_value: 86400
  },

  %{
    name: "Critical Servers - Special Handling",
    template_name: "critical_servers",
    template_description: "Never suppress alerts from critical servers",
    action: "tag",
    add_tags: ["critical_server", "do_not_suppress"],
    priority: 100,
    is_template: true,
    description: """
    Use exemptions to ensure critical servers are never suppressed.
    This template adds tags and should be combined with exempted_agent_ids
    on other suppression rules to create exceptions.
    """,
    time_window_type: "indefinite"
  }
]

IO.puts("Creating suppression rule templates...")

Enum.each(templates, fn template_attrs ->
  attrs = Map.merge(template_attrs, %{
    organization_id: system_org.id,
    enabled: false  # Templates are disabled by default
  })

  case Repo.get_by(SuppressionRule,
    organization_id: system_org.id,
    template_name: attrs.template_name
  ) do
    nil ->
      %SuppressionRule{}
      |> SuppressionRule.changeset(attrs)
      |> Repo.insert!()
      IO.puts("  ✓ Created template: #{attrs.template_name}")

    existing ->
      existing
      |> SuppressionRule.changeset(attrs)
      |> Repo.update!()
      IO.puts("  ↻ Updated template: #{attrs.template_name}")
  end
end)

IO.puts("\nSuppressionRule templates created successfully!")
IO.puts("These templates can be found in the 'Templates' tab of the Suppression Rules UI.")
