defmodule TamanduaServerWeb.GraphQL.Types.AlertTypes do
  @moduledoc """
  GraphQL types for Alerts.
  """
  use Absinthe.Schema.Notation

  @desc "Alert severity level"
  enum :severity do
    value :critical, description: "Critical severity - immediate action required"
    value :high, description: "High severity - urgent attention needed"
    value :medium, description: "Medium severity - should be investigated"
    value :low, description: "Low severity - informational"
    value :info, description: "Informational - no action needed"
  end

  @desc "Alert status"
  enum :alert_status do
    value :new, description: "New, unacknowledged alert"
    value :investigating, description: "Under investigation"
    value :resolved, description: "Resolved alert"
    value :false_positive, description: "Marked as false positive"
  end

  @desc "A security alert generated by detection engines"
  object :alert do
    field :id, non_null(:id), description: "Unique alert identifier"
    field :title, non_null(:string), description: "Alert title"
    field :description, :string, description: "Detailed description"
    field :severity, non_null(:string), description: "Alert severity level"
    field :status, non_null(:string), description: "Current alert status"
    field :threat_score, :float, description: "Threat score (0.0-1.0)"
    field :resolution_notes, :string, description: "Resolution notes"
    field :event_ids, list_of(:id), description: "Related event IDs"
    field :source_event_id, :id, description: "Source event that triggered the alert"
    field :mitre_tactics, list_of(:string), description: "MITRE ATT&CK tactics"
    field :mitre_techniques, list_of(:string), description: "MITRE ATT&CK techniques"
    field :enrichment, :json, description: "Enrichment data"
    field :evidence, :json, description: "Evidence collected"
    field :process_chain, list_of(:process_chain_entry), description: "Process chain"
    field :raw_event, :json, description: "Raw event data"
    field :detection_metadata, :json, description: "Detection engine metadata"
    field :contributing_events, list_of(:string), description: "Contributing event IDs"
    field :inserted_at, :datetime, description: "Alert creation timestamp"
    field :updated_at, :datetime, description: "Last update timestamp"

    field :agent_id, :id
    field :organization_id, :id
    field :assigned_to_id, :id

    field :agent, :agent do
      resolve &TamanduaServerWeb.GraphQL.Resolvers.AlertResolver.agent/3
    end

    field :assigned_to, :user do
      resolve &TamanduaServerWeb.GraphQL.Resolvers.AlertResolver.assigned_to/3
    end

    field :related_events, list_of(:event) do
      arg :limit, :integer, default_value: 20
      resolve &TamanduaServerWeb.GraphQL.Resolvers.AlertResolver.related_events/3
    end

    field :timeline, list_of(:timeline_event) do
      resolve &TamanduaServerWeb.GraphQL.Resolvers.AlertResolver.timeline/3
    end
  end

  @desc "Process chain entry in alert evidence"
  object :process_chain_entry do
    field :pid, :integer
    field :ppid, :integer
    field :name, :string
    field :path, :string
    field :cmdline, :string
    field :user, :string
    field :sha256, :string
    field :is_elevated, :boolean
    field :is_signed, :boolean
    field :signer, :string
    field :start_time, :datetime
  end

  @desc "Timeline event for investigation"
  object :timeline_event do
    field :timestamp, :datetime
    field :event_type, :string
    field :description, :string
    field :details, :json
    field :severity, :string
    field :agent_id, :id
    field :event_id, :id
  end

  @desc "Alert statistics"
  object :alert_stats do
    field :total, non_null(:integer), description: "Total number of alerts"
    field :new, non_null(:integer), description: "New alerts"
    field :investigating, non_null(:integer), description: "Alerts under investigation"
    field :resolved, non_null(:integer), description: "Resolved alerts"
    field :by_severity, :json, description: "Alert count by severity"
    field :by_tactic, :json, description: "Alert count by MITRE tactic"
    field :trend, list_of(:alert_trend_point), description: "Alert trend over time"
  end

  @desc "Alert trend data point"
  object :alert_trend_point do
    field :timestamp, :datetime
    field :count, :integer
    field :severity, :string
  end

  @desc "Filter input for alerts"
  input_object :alert_filter do
    field :status, :string, description: "Filter by status"
    field :severity, :string, description: "Filter by severity"
    field :agent_id, :id, description: "Filter by agent"
    field :assigned_to_id, :id, description: "Filter by assignee"
    field :mitre_tactic, :string, description: "Filter by MITRE tactic"
    field :mitre_technique, :string, description: "Filter by MITRE technique"
    field :since, :datetime, description: "Alerts since timestamp"
    field :until, :datetime, description: "Alerts until timestamp"
    field :search, :string, description: "Full-text search in title/description"
    field :threat_score_min, :float, description: "Minimum threat score"
  end

  @desc "Input for updating an alert"
  input_object :update_alert_input do
    field :status, :string, description: "New status"
    field :severity, :string, description: "New severity"
    field :resolution_notes, :string, description: "Resolution notes"
    field :assigned_to_id, :id, description: "Assign to user"
  end

  @desc "Input for bulk alert operations"
  input_object :bulk_alert_input do
    field :alert_ids, non_null(list_of(non_null(:id))), description: "Alert IDs to update"
    field :status, :string, description: "New status for all"
    field :assigned_to_id, :id, description: "Assign all to user"
  end
end
