defmodule TamanduaServer.ProductStatus do
  @moduledoc """
  Surfaces the project's honest validation-gate state for UI banners and
  analyst-facing reminders.

  This is sourced from the read-only authority artifact
  `docs/benchmarks/generated/validation_product_readiness_summary.json`,
  which is regenerated by the validation tooling and MUST NOT be hand-edited.

  Strategy doctrine (see CLAUDE.md): the project is Advanced Alpha, OSS-led.
  Honest labels and gate numbers stay verbatim — operators must never confuse
  UI completeness with production readiness.

  The JSON is read at compile time via `@external_resource` so there is no
  per-render I/O. If the artifact cannot be located or parsed at compile
  time, we fall back to safe defaults that still reflect the alpha state
  rather than silently hiding the banner.
  """

  # Relative path from this module's source file location to the validation
  # authority JSON. Resolved against the mix project root at compile time.
  @status_relative_path "../../../../docs/benchmarks/generated/validation_product_readiness_summary.json"
  @status_path Path.expand(@status_relative_path, __DIR__)

  # Conservative fallback that still keeps the alpha label visible if the
  # authority artifact disappears or can't be parsed. We deliberately do NOT
  # fall back to a "passing" state.
  @fallback %{
    label: "Advanced Alpha",
    closure: "unknown",
    preflight: "unknown",
    dispatch: "unknown",
    product_ready: false,
    generated_at: nil,
    source_available: false
  }

  decoded =
    case File.read(@status_path) do
      {:ok, body} ->
        case Jason.decode(body) do
          {:ok, parsed} -> {:ok, parsed}
          {:error, reason} -> {:error, {:decode_error, reason}}
        end

      {:error, reason} ->
        {:error, {:read_error, reason}}
    end

  case decoded do
    {:ok, parsed} ->
      @external_resource @status_path

      gates = Map.get(parsed, "gates", %{})
      closure = get_in(gates, ["closure", "coverage"]) || "unknown"
      preflight = get_in(gates, ["preflight", "coverage"]) || "unknown"
      dispatch = get_in(gates, ["dispatch", "coverage"]) || "unknown"
      product_ready = Map.get(parsed, "product_ready", false)
      generated_at = Map.get(parsed, "generated_at")

      @status %{
        label: "Advanced Alpha",
        closure: closure,
        preflight: preflight,
        dispatch: dispatch,
        product_ready: product_ready,
        generated_at: generated_at,
        source_available: true
      }

    {:error, _reason} ->
      @status @fallback
  end

  @doc """
  Returns the validation-gate state as a map with string-friendly fields.

  Keys:
    * `:label`            - honest product label (e.g. "Advanced Alpha")
    * `:closure`          - closure gate coverage (e.g. "0/23")
    * `:preflight`        - preflight gate coverage (e.g. "6/8")
    * `:dispatch`         - dispatch gate coverage (e.g. "0/6")
    * `:product_ready`    - boolean from authority artifact
    * `:generated_at`     - ISO-8601 timestamp from the authority artifact (or nil)
    * `:source_available` - whether the authority JSON was readable at compile time
  """
  @spec status() :: map()
  def status, do: @status

  @doc """
  Returns a single-line summary suitable for the banner body, e.g.
  `"closure 0/23, preflight 6/8, dispatch 0/6"`.
  """
  @spec gate_summary() :: String.t()
  def gate_summary do
    "closure #{@status.closure}, preflight #{@status.preflight}, dispatch #{@status.dispatch}"
  end

  @doc """
  Public link to the validation scope document rendered in the banner.
  """
  @spec gaps_url() :: String.t()
  def gaps_url do
    "https://github.com/treant-lab/tamandua-community/blob/main/docs/community/PUBLIC_ALPHA_PRODUCT_VALIDATION_CHECKLIST.md"
  end
end
